inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
   NewCops: enable
   Exclude:
     - 'node_modules/**/*'
     - 'vendor/**/*'
     - 'bin/*'
     - 'log/**/*'
     - 'public/**/*'
     - 'tmp/**/*'
     - '.git/**/*'
     - 'storage/**/*'
     - 'lib/**/*'
     - db/schema.rb
     - Guardfile

Style/Documentation:
  Exclude:
    - 'db/migrate/*'
    - 'config/**/*'
    - 'app/helpers/*'

