connect:
  host: <%= ENV.fetch('RABBITMQ_HOST', 'localhost') %>
  port: <%= ENV.fetch('RABBITMQ_PORT', '5672') %>
  username: <%= ENV.fetch('RABBITMQ_USER', 'guest') %>
  password: <%= ENV.fetch('RABBITMQ_PASSWORD', 'guest') %>

exchange:
  transaction_checker:
    name: meduza.transaction_checker
    type: direct

queue:
  transaction_checker:
    name: meduza.transaction_checker
    durable: true

# Bind amqp daemon to queue and exchange.
binding:
  transaction_checker:
    queue: transaction_checker
    # clean_start: true
    exchange: transaction_checker

channel:
  transaction_checker:
    prefetch: 10
