connect:
  host: <%= ENV.fetch('RABBITMQ_HOST', 'localhost') %>
  port: <%= ENV.fetch('RABBITMQ_PORT', '5672') %>
  username: <%= ENV.fetch('RABBITMQ_USER', 'guest') %>
  password: <%= ENV.fetch('RABBITMQ_PASSWORD', 'guest') %>

exchange:
  meduza:
    name: meduza
    type: direct

binding:
  address_pender:
    exchange: meduza
    queue: meduza.check_address
    durable: true
    type: direct
    routing_key: check_address

  transaction_pender:
    exchange: meduza
    queue: meduza.check_transaction
    durable: true
    type: direct
    routing_key: check_transaction

channel:
  meduza:
    prefetch: 10
