connect:
  host: <%= ENV.fetch('RABBITMQ_HOST', 'localhost') %>
  port: <%= ENV.fetch('RABBITMQ_PORT', '5672') %>
  username: <%= ENV.fetch('RABBITMQ_USER', 'guest') %>
  password: <%= ENV.fetch('RABBITMQ_PASSWORD', 'guest') %>

exchange:
  meduza:
    name: meduza
    type: direct

binding:
  check_transaction:
    exchange: meduza
    queue: meduza.check_transaction
    queue_options:
      durable: true
    type: direct
    routing_key: check_transaction
    # clean_start: true

  legacy_rpc_callback:
    exchange: meduza
    queue: meduza.legacy_rpc_callback
    type: direct
    routing_key: legacy_rpc_callback

channel:
  meduza:
    prefetch: 10
